In [1]:
#Variables
age=21
height=5.4
name="Pranitha"
is_student=True

In [2]:
print("Age:", age)
print("Height:", height)
print("Name:", name)
print("Is student:", is_student)

Age: 21
Height: 5.4
Name: Pranitha
Is student: True


In [12]:
#Slicing
word='Computer'
print(word[1:5])
#step
print(word[0:8:2])

ompu
Cmue


Types of objects in py

1.immutable obj - The value which cannot be changed once it is created(int,float,string,bool,tuple).

2.mutable objs - The value which can be changed once it is created(list,set,dictionary).

In [25]:
#List
list1=[20,43,43,35]
list1.append(5)
list1.remove(20)
print('\n marks:',list1)
print('1st marks',list1[0])
print('total marks',len(list1))


 marks: [43, 43, 35, 5]
1st marks 43
total marks 4


In [23]:
#Tuples
shape=(24,334,23,23)
print('\n image shape:',shape)
print(shape[1])


 image shape: (24, 334, 23, 23)
334


list and tuples allows duplicate values

In [22]:
#Set
num={4,64,43,54}
print(num)

{64, 43, 4, 54}


In [27]:
#Dictionaries(key-value pairs)
student={'name':'Pranitha','age':21,'height':5.,'age':21}
print('student name=', student['name'])
print('student age=', student['age'])
print('student height=', student['height'])
print(student)

student name= Pranitha
student age= 21
student height= 5.0
{'name': 'Pranitha', 'age': 21, 'height': 5.0}


set and dict does not duplicate values

Operations in py

1. Arthimetic
2. Assignment
3. Comparison
4. Logical
5. Identity
6. Membership


In [31]:
a=int(input('enter the num'))
b=int(input('enter the num'))
if(a>b):
  print('a is greatest')
else:
  print('b is greatest')

enter the num45
enter the num67
b is greatest


In [33]:
a=45
b=54
c=43
if(a>b and a>c):
  print('a is greatest')
elif(b>a and b>c):
  print('b is greatest')
else:
  print('c is greatest')

b is greatest


In [35]:
#for loop
nums=[32,43,53,54]
for i in nums:
  print(i)

32
43
53
54


In [38]:
#while loop
i=0
while i<7:
  print(i)
  i+=1

0
1
2
3
4
5
6


In [2]:
#without using func
number=int(input("enter the factorial number:"))
factorial=1
if number==0:
  print("factorial of 0 is 1")
else:
    for i in range(1,number+1):
      factorial=factorial*i
    print("factorial of",number,"is",factorial)

enter the factorial number:9
factorial of 9 is 362880


In [7]:
#with using func
def factorial_num(num):
  factorial=1
  if num==0:
    return factorial
  else:
    for i in range(1,num+1):
      factorial=factorial*i
    return factorial


In [8]:
print(factorial_num(4))

24


In [9]:
#numpy
import numpy as np

In [44]:
import numpy as np
a=np.random.random((3,4))
print(a)

[[0.30439966 0.11269071 0.33350199 0.40921946]
 [0.72936562 0.55036363 0.32612121 0.77162508]
 [0.13884206 0.08218381 0.19277389 0.97552726]]


In [52]:
b=np.random.randint(2,100,(5,6))
print(b)
print(b.shape)
print(b.size)

[[54 35 91 32 55 58]
 [76 75 17 99 88 97]
 [76 56 25 14 56 84]
 [64 94 82 56 63 26]
 [ 4 87 75 31 48 23]]
(5, 6)
30
